spring:
  main:
      allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/quick_auction
    username: postgres
    password: postgres
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 9000
jwt:
  token:
    secret: VerYSecRet
    expired: 7200000

